# set up speechmatics image

# Login to speechmatics docker
speechmatics-docker-login:
	docker login https://speechmatics-docker-demo.jfrog.io

pull-speechmatics-image:
	docker pull speechmatics-docker-demo.jfrog.io/batch-asr-transcriber-de-hydra:1.0.0.16

build-custom-image:
	@echo build and tag image custom image
	docker build -t speechmatics-custom/transcriber-de:1.00 .

## Docker run commands
# basic docker run
basic-docker-run:
	docker run -i -e \
	LICENSE_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJmZWF0dXJlcyI6WyJNQVBSVCIsIk1BUEJBIiwiQU1DQyIsIkFQRCIsIkFQUiIsIkFTUyIsIkFPUDIiXSwiY29udHJhY3RpZCI6IiIsImlzX3RyaWFsIjpmYWxzZSwiZXhwIjoxNjI0MjMzNjAwLCJqdGkiOiI0MzQzMWIwN2FjOWY0ZTFmODg3YTU5M2JhYzNmNGU2ZCIsImlhdCI6MTYyMjEyMjI4NiwiaXNzIjoiU3BlZWNobWF0aWNzIiwibmJmIjoxNjIyMDczNjAwLCJzdWIiOiJOZXVyYXN3aXRjaCJ9.gibI9o0KOTS7I3RnOngsAzac_dtYMF-PuRwIWcCPndSo_nZ1DP76emh6mTHdWFvb0GiEg902zyjG-wMO1nl_3yIWWCjCWOlifkckQ8h_kvh54nQ2dJSdQSwy6F6GDc73ybMc-geWFhRu30XZTdRZ21cSb6MlWspFzzEJtSCbq97GnFTyG4Bbo2n2G49iC4azOvtgIesZ9uMwgzhnqK863bOkIxKqNhm2aCgmYLHC9c-vxT79EDU9Os7WyZzeZmXcogAAuZOWYhfZ9fyd7RS5FYJHTx9vgFzu_GnLoabCSAAhMSybKtZaUVktYFIzgErlJbzFDMpXn8gcYQ1bVoM6lA \
	speechmatics-docker-demo.jfrog.io/batch-asr-transcriber-en:8.1.2

# docker run with logging
docker-run-logging:
	docker --rm -e SM_JOB_ID=123 -e SM_LOG_DIR=/logs \ \
	LICENSE_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJmZWF0dXJlcyI6WyJNQVBSVCIsIk1BUEJBIiwiQU1DQyIsIkFQRCIsIkFQUiIsIkFTUyIsIkFPUDIiXSwiY29udHJhY3RpZCI6IiIsImlzX3RyaWFsIjpmYWxzZSwiZXhwIjoxNjI0MjMzNjAwLCJqdGkiOiI0MzQzMWIwN2FjOWY0ZTFmODg3YTU5M2JhYzNmNGU2ZCIsImlhdCI6MTYyMjEyMjI4NiwiaXNzIjoiU3BlZWNobWF0aWNzIiwibmJmIjoxNjIyMDczNjAwLCJzdWIiOiJOZXVyYXN3aXRjaCJ9.gibI9o0KOTS7I3RnOngsAzac_dtYMF-PuRwIWcCPndSo_nZ1DP76emh6mTHdWFvb0GiEg902zyjG-wMO1nl_3yIWWCjCWOlifkckQ8h_kvh54nQ2dJSdQSwy6F6GDc73ybMc-geWFhRu30XZTdRZ21cSb6MlWspFzzEJtSCbq97GnFTyG4Bbo2n2G49iC4azOvtgIesZ9uMwgzhnqK863bOkIxKqNhm2aCgmYLHC9c-vxT79EDU9Os7WyZzeZmXcogAAuZOWYhfZ9fyd7RS5FYJHTx9vgFzu_GnLoabCSAAhMSybKtZaUVktYFIzgErlJbzFDMpXn8gcYQ1bVoM6lA \
	speechmatics-docker-demo.jfrog.io/batch-asr-transcriber-en:8.1.2 \
	-stderr



